server:
  port: 8443

logging:
  file:
    name: ./log/bot.log

spring:
  application:
    name: bot
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
  data:
    redis:
      host: 192.168.1.100
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${BAILIAN_KEY}
      chat:
        options:
          model: qwen-max-0125
          max-tokens: 1000

bot:
  app-id: ${QQ_BOT_APP_ID}
  app-secret: ${QQ_BOT_APP_SECRET}
  token-key: access_token:${bot.app-id}


