server:
  port: 60001
logging:
  charset:
    file: UTF-8
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
  file:
    name: ./log/bot-core.log

bot:
  baseUrl: https://api.sgroup.qq.com

amap:
  baseUrl: https://restapi.amap.com